modLoader="javafml"
loaderVersion="[${loader},)"
license="MIT"

[[mods]]
modId="acousticsystem"
version="${version}"
displayName="AcousticSystem"
description='''Real-time sound occlusion, diffraction, reflection, reverb and fluid acoustics.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.acousticsystem]]
modId="forge"
mandatory=true
versionRange="[${loader},)"
ordering="NONE"
side="CLIENT"

[[dependencies.acousticsystem]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft}]"
ordering="NONE"
side="CLIENT"
